theme: jekyll-theme-midnight
title: woke
description: Detect non-inclusive language in your source code.

google_analytics: UA-203072039-1
show_downloads: true
github:
  repository_url: https://github.com/get-woke/woke
  zip_url: https://github.com/get-woke/woke/releases/latest
  tar_url: https://github.com/get-woke/woke/releases/latest
