remote_theme: caitlinelfring/jekyll-theme-midnight
title: woke
description: Detect non-inclusive language in your source code.

google_analytics: UA-203072039-1
show_downloads: true
github_override:
  repository_url: https://github.com/get-woke/woke
  zip_url: https://github.com/get-woke/woke/releases/latest
  tar_url: https://github.com/get-woke/woke/releases/latest
  owner_url: https://github.com/caitlinelfring
  owner_name: Caitlin Elfring
